services:
  dashboard:
    build:
        context: .
        dockerfile: Dockerfile
    image: streamlit
    environment:
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_CONTAINER_NAME: ${AZURE_CONTAINER_NAME}
    restart: always
    ports:
      - "8585:8585"